import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      backgroundColor: "#1C1C1E",
      display: "flex",
      maxWidth: 480,
      width: "100%",
      flexDirection: "column",
      alignItems: "center",
      margin: "0 auto",
      padding: "80px 0 44px",
    },
    header: {
      color: "#FFF",
      textAlign: "center",
      marginTop: 11,
      fontFamily: "Integral CF, sans-serif",
      fontWeight: "700",
      fontSize: 20,
      lineHeight: "150%",
      padding: "5%",
    },
    headerText: {
      color: "#FFF",
      fontSize: 25,
      fontFamily: "ABeeZee",
      padding: "5%",
      fontWeight: "900",
    },
    content: {
      display: "flex",
      marginTop: "10%",
      padding: "7%",
      width: "100%",
      height: "100%",
      maxWidth: 312,
      alignItems: "stretch",
      gap: 20,
      fontSize: 20,
      color: "#000",
      fontWeight: "bold",
      whiteSpace: "nowrap",
      textAlign: "center",
      justifyContent: "space-between",
    },
    mainImage: {
      position: "relative",
      width: 54,
      flexShrink: 0,
      aspectRatio: 1,
    },
    textContainer: {
      justifyContent: "center",
      alignItems: "start",
      borderRadius: 48,
      display: "flex",
      flexDirection: "column",
      margin: "auto 0",
      padding: 13,
      flex: 1,
    },
    buttonContainer: {
      justifyContent: "center",
      alignItems: "start",
      borderRadius: 48,
      backgroundColor: "#D0FD3E",
      display: "flex",
      flexDirection: "column",
      margin: "auto 0",
      padding: 13,
      flex: 1,
    },
    buttonText: {
      fontFamily: "Open Sans, sans-serif",
      textAlign: "center",
    },
    buttonIcon: {
      position: "relative",
      width: 24,
      flexShrink: 0,
      aspectRatio: 1,
    },
  });